# Project 2 course layer.
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "advembeddedp2"
BBFILE_PATTERN_advembeddedp2 = "^${LAYERDIR}/"
BBFILE_PRIORITY_advembeddedp2 = "7"
LAYERSERIES_COMPAT_advembeddedp2 = "kirkstone langdale mickledore nanbield scarthgap"
LAYERDEPENDS_advembeddedp2 = "core openembedded-layer"
